### ISSUE TITLE
Duplicate userid generates unhandled errors

### ISSUE THREAD

**Issue by boredompwndu** [danbuis/full_thrust_pbp#8]
![image](https://user-images.githubusercontent.com/8730661/216871079-c20b5ce2-18db-4241-82c6-534583c441ab.png)

This is good actually?

**Comment by danbuis** [comment]
Eh, I'd like a better error message, one that doesn't involve the console tools to find.

It would be nice if that was part of the form validation, and shouldn't be too hard

**Comment by danbuis** [comment]
Closing as its a repeat of #1
